NotionX/react-notion-x

packages/react-notion-x/package.json
`react-notion-x` should not use its own React, but its parent's, as using two different React copies might cause problems. While usually package managers deduplicate dependencies, in some cases they might choose not to (and the semantics of `node`'s package system don't force them to deduplicate either). Declaring `react` and `react-dom` as peer dependencies will make clear that they have to use the parent's copy, and declaring it in the `devDependencies` will make sure that they are available for local development and testing.
=> Use React of the parent project instead of our own

packages/notion-client/src/notion-api.ts
I tried ``notion-client`` on a server project, with authToken getPage() was giving Me ``Notion page not found`` on a page on other workspace I'm a member of.
After I inspected notion.so in Devtools, I found out that a ``x-notion-active-user-header`` header is added to the request. I implemented this by changing your code locally, and it worked.
=> + activeUser for accounts with multiple workspaces

packages/react-notion-x/src/styles.css
change object-fit in svg.notion-page-icon
using object-fit cover
using object-fit fill
=> Update styles.css changed svg.notion-page-icon to object-fit: fill

packages/notion-utils/src/get-page-content-block-ids.ts
Some notion pages have this value[1] empty. At that time, id is undefined and an error will occur in the subsequent processing, so I tried not to add it if it is empty.
=> fix no value at content block id

packages/react-notion-x/src/block.tsx
Fix empty Notion toggles and possible empty image titles
Public notion page example: https://www.notion.so/Test-Empty-130868ef58d949f4add8cf1da983fc16
Id: 130868ef58d949f4add8cf1da983fc16
With out this change the above notion page would get the error:
Typer Error cannot read property 'title' of undefined
=> Typer Error cannot read property 'title' of undefined

packages/react-notion-x/src/components/collection-card.tsx
`
TypeError: Cannot read property 'filter' of undefined
at CollectionCard (/Users/noahbragg/Developer/node_projects/potion/potion-site-v2/node_modules/react-notion-x/build/cjs/components/collection-card.js:83:22)
`
Happens on this page: https://www.notion.so/ad83934d2fe94e8dba592c8547d6a026?v=7a75440935c44dc88e4dcfcf2b87f28f
=> fixed filter possibly being undefined in collection card

packages/react-notion-x/src/components/collection-card.tsx
This issue is related to the last PR in a case when properties is null. Just skipping that property when there is no data.
Happens on this page: https://www.notion.so/ad83934d2fe94e8dba592c8547d6a026?v=7a75440935c44dc88e4dcfcf2b87f28f
=> fixed block.properties being undefined in collection-card

packages/react-notion-x/src/block.tsx
Fixed columns for safari and other browsers.
Notion page id for example: 067dd719a912471ea9a3ac10710e7fdf
After some playing around I found that px was causing safari to fail calculating the width where as chrome was smarter than that. 😂
=> fixed width for columns in browsers such as safari

packages/react-notion-x/src/components/asset.tsx
Video assets url has two youtube url type ,  "youtube.com" and "youtu.be".
if url has "youtu.be", display iframe.
test with this page please.
https://www.notion.so/nabettu/youtube-test-cf528ab5f3374ada859cfa9ea450fad9
=> YouTube Video Url has "youtube.com" and "youtu.be"

packages/react-notion-x/src/components/property.tsx
Currently react-notion-x doesn't have pages for each row in a table. I added linking to a page in a table collection view.
Here is a little video showing the new functionality: https://www.loom.com/share/15cd7ec66aaf466eb0e6699812e1cd85
This more closely matches how Notion behaves with tables.
Tested on e5b45193b4c1436fbde24cad8e9ababd has a table in there among other things.
=> Added links to pages in table rows

packages/react-notion-x/src/renderer.tsx
`minTableOfContentsItems` in props was not working properly.
I think I'll be able to change `minTableOfContentsItems = 3`.
https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/a1f240931536d30c225741c38087d66b85e5f0c5/components/NotionPage.tsx#L128
test
https://www.notion.so/suu35/TableOfContents-f5dc8b907d2e427b830836d8f78c0a41
=> Fixed minTableOfContentsItems not working.

packages/react-notion-x/src/components/lazy-image.tsx
Alt text from a caption just wasn't added to the image in lazy-image. Added it in this PR.
The preview image was already good to go.
Can see it tested out in the test suite page id: 3492bd6dbaf44fe7a5cac62c5d402f06
=> Added alt text to images from the caption

packages/react-notion-x/src/components/text.tsx
Here is a page to test where I saw the issue: 4d967aaf8f204b30a0f50c74f2801987
You can see down about half way the FAQ title and first title of the toggle aren't showing. I found this was because the page had comments there.
The change I made was make the "m" decoration (comments) still return the element instead of skipping it.
=> Fix text being empty when there is a comment on the block.

packages/notion-utils/src/get-text-content.ts
A text content in Notion may include '⁍' for TeX equations and '‣' for mentions. So I changed the code a little bit to exclude this two marks. The `getTextContent` function is used in may places like toc, formula, title of collection, etc. This commit will make those elements display better.
Sample Notin Page ID: e2e6389a160e406d88e312f12ede26e4
By the way, I really appreciate your remarkable work! Just started to use react-notion-x, I hope I can contribute a little bit to this great project.
=> fix get text to exclude marks for TeX and mention

packages/react-notion-x/src/components/collection-view-board.tsx, packages/react-notion-x/src/components/collection-view-gallery.tsx, packages/react-notion-x/src/components/collection-view-list.tsx, packages/react-notion-x/src/components/collection-view-table.tsx
Not sure it is intended, collection view components print out some debugging info on browsers or server logs. Hope it is able to control its verbose level in the future. Gently suggesting commenting those out in production.
=> Comment out debug logs of collection views

packages/react-notion-x/src/block.tsx
If no language is set in notion code block, this line will yield an error:
```
Cannot read property '0' of undefined
```
See https://github.com/craigary/nobelium/issues/130
=> fix property error if no language is set in code block

packages/react-notion-x/src/utils.ts
Interesting issue in grouping block content where a block is missing so the value is undefined. Somehow its getting past the null check so then trys to access the array at index -1
happening on this notion page: b1e94e2308b24476a323fcaa6fa1a906
=> fixed groupBlockContent trying to access index -1

packages/notion-types/src/block.ts, packages/react-notion-x/src/block.tsx
Here is a notion page id to test on: 54ffff21b193431f98651dc2d776ab34
Just adds the caption to the code block if there is one.
The text right underneath the block is a caption in this image.
=> Added captions for code blocks

packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/renderer.tsx
Closes #84 
This PR adds an optional new parameter `hideBlockId` to the `NotionRenderer`:
```javascript
<NotionRenderer recordMap={recordMap} fullPage={true} darkMode={false} hideBlockId={true} />
```
If set to true then the `blockId` used to generate HTML classes is hardcoded to `notion-block`, instead of appending the Notion block ID. This allows a (server rendered) library user to keep the Notion page block ID private, which reduces the downside of needing to make a page public while react-notion-x can't use the official API.
If not passed (ie by default) block IDs remain unchanged, the change is entirely opt-in.
=> Add support for hideBlockId param on NotionRenderer

packages/react-notion-x/src/components/collection-view-board.tsx
Example of this issue on this page id: 7d3913ebc76a4ac1abc20e5a12bec55a
When the board is in a toggle the `groupResults` data is not present.
I couldn't find it anywhere else in the block either. So we aren't able to render the table when its inside a toggle.
The data without groupResults
The data with groupResults
May need extra 👀 on this. But I'm not seeing away we can render the table in this case.
So for now I am return null if the `groupResults` is not there.
=> Fixed board collection in toggle causing crash

packages/react-notion-x/src/components/graceful-image.tsx, packages/react-notion-x/src/utils.ts
This PR updates `GracefulImage` so that when rendered in a non-browser environment it falls back to an `<img>` element instead of using react-image's `<Img>`. This allows static server rendering to correctly render images. Note that react-image deliberately does not SSR images: https://github.com/mbrevda/react-image/issues/206 (it renders nothing if only the src is provided which is how react-notion-x uses it)
In a browser the behaviour is unchanged. The props taken by `<GracefulImage` are unchanged.
Note that for simplicity the props are used as-is for the `<img>` element, and I've used a ts-ignore for this. Basically if rendering `<GracefulImage>` on the server, it acts as a plain `<img>` and only props for that tag will be relevant. I don't think it's worth doing anything more …
=> Allow SSR for GracefulImage

packages/notion-types/src/block.ts, packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/components/sync-pointer-block.tsx, packages/react-notion-x/src/renderer.tsx
The new Notion sync block is here. Now react-notion-x can support this.
I exported the NotionBlockRenderer sot that functionality could be used for the reference blocks.
Test page on: 8bcd65801a5d450fb7218d8890a38c29
=> Added support for sync blocks

packages/react-notion-x/src/components/asset.tsx
Testing pageId: 24d647e9865f44bb833448d3ba36c264
Video embed company owned by Typeform apparently.
=> Added support for videoask embeds

packages/react-notion-x/src/block.tsx
Notion classNames were removed to using uuid instead of id like they were in the past. Reverting this back.
=> fixed notion block className not using id

packages/react-notion-x/src/components/search-dialog.tsx, packages/react-notion-x/src/types.ts
Testing on this public notion id: e8da438394ba45f19ff4469b239e23ab
Here is the problem. mapPageUrl doesn't have the correct recordMap for all the search pages. So then you can't create the correct url for search results using automatic urls for example.
So when searching you get this:
Now you can pass the results recordMap in and have more info to create the results needed for mapPageUrl. So you get this now.
You could create a wrapper around this to pass a generic mapPageUrl into the NotionRenderer. But that recordMap only has the pages in the recordmap for that page. It doesn't have all the nested pages of a multilayer document.
This is also backwards compatible as recordMap can be undefined.
=> Fixed search not having the right recordmap

packages/react-notion-x/src/block.tsx
empty bookmarks cause an error because some data isn't there. Just returning null when there is no link added to the bookmark.
Also prettified some code so that was the other change.
Notion page id to test: 7f266f5bfd9f48158d4aba0245ca43cb
=> fixed empty bookmark causing error

packages/notion-client/src/notion-api.test.ts, packages/notion-client/src/notion-api.ts, packages/notion-types/src/collection-view.ts, packages/react-notion-x/src/components/collection-view-board.tsx
Testing on: https://www.notion.so/potionsite/newest-board-a899b98b7cdc424585e5ddebbdae60cc
Issue: https://github.com/NotionX/react-notion-x/issues/104
Looks like Notion changed the name in collectionview.format from board_groups2 to board_columns.
We grab the queryCollection data and add it on to the recordMap. That notion endpoint was failing because it didn't have the right query params with the name change.
=> Fix for board collections

packages/react-notion-x/src/block.tsx
I use react-notion-x for my personal website and it's awesome!
But I figured out an issue with the main title when using the `fullPage` option.
Example on my website: https://shellbear.me/blog/go-dokku-deployment 
The `notion-title` is wrapped inside a div. It should be a  `h1` instead for SEO and best practices.
If you compare with any website made with super.so, the title is always a `h1`.
Example on a random website made with super.so: https://clip.super.so/
Thank you 👋
=> Use h1 instead of div for notion-title

packages/react-notion-x/src/block.tsx
NotionId to test on: 067dd719a912471ea9a3ac10710e7fdf
Updated the Notion subheader blocks to have h2 h3 annd h4 tags for better seo.
The notion page title already takes the h1 tag so...
Notion h1 block -> h2 tag
Notion h2 block -> h3 tag
Notion h3 block -> h4 tag
added the new tags in a way that the previous header style classes shouldn't be affected and there shouldn't be any breaking style changes.
Possible that we won't want the tags to wrap as much content and be closer to the text itself? This seems good enough though.
=> added h2 h3 and h4 tags for notion header blocks

packages/notion-types/src/block.ts, packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/components/asset-wrapper.tsx, packages/react-notion-x/src/components/asset.tsx
Notion page id to test: 5d3638cec4a54a38848af636c5dd3935
Test both a google sheet embed as well as a google drive.
Created the AssetWrapper so there isn't duplicate code around assets.
=> added support for google sheets embed, added asset wrapper component

packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/styles.css
example: https://potionsite.notion.site/Syncs-67be5281858f414da27b469043a21a0d
Issue:
sync block doesn't take full width of the page content. Causes certain blocks like divider to be squished.
Before:
After:
renamed the sync-block class to notion-sync-block to be more consistent.
=> fix sync block width not being full width

packages/react-notion-x/src/styles.css
Two issues in this PR.
1. blocks in callouts show links on new lines and don't take up the full width.
2. page mentions have 2 underlines because its a link as well as a page
page to test: https://potionsite.notion.site/Callout-9465a22dc9734fc1a9182d9f179b47fa
Before
After
=> Callout inline and link issues

packages/react-notion-x/src/components/collection-view-list.tsx
id to test where this usecase happens: 6acb5043abcf4966a47244b03ca61a88
The block in collections could be null causing errors in the collection. just throwing out the row if we don't have the data.
=> Fix block being null in collections

packages/react-notion-x/src/components/asset-wrapper.tsx, packages/react-notion-x/src/components/asset.tsx
Testin on: 3492bd6dbaf44fe7a5cac62c5d402f06
Made captions aligned with images. Before they were right aligned even when the image is centered
Made images like this one clickable with a link.
To do this set the caption to be just a valid url or a notion page id.
like https://google.com or /3492bd6dbaf44fe7a5cac62c5d402f06
=> Fix image caption and make images with url captions a link

packages/react-notion-x/src/components/asset.tsx
There was a bug where no captions could be seen except for images.
Embed captions were hidden by the embed.
So I moved captions outside of the asset block for embeds. The images caption needs to stay inside the asset so it can have the correct styling when an image is centered.
PageId to test: 5d4e290ca4604d8fb809af806a6c1749
Fixed image example
Fixed embed example
=> Made it so captions on embeds can be seen

packages/notion-utils/src/get-canonical-page-id.ts
=> feat: support for normalize chinese title

packages/react-notion-x/src/components/collection-view-board.tsx
Fixed board view not having all of the cards after adding groupedBy for tables.
pageId: dd5d904fb13d402cbba6d6bdfecfa181
=> fixed uncategorized issue for board views

packages/notion-types/src/block.ts, packages/react-notion-x/src/block.tsx
Only allows you to link to pages that are in the same workspace.
Previously we had supported page links though the page mention block and text block page links.
This PR actually supports the Notion Page Link block as well.
Example of page link block here: 52353862df0f48ba85648db7d0acd1dd
=> added the block for page links

packages/react-notion-x/src/styles.css
Related to this issue [https://github.com/NotionX/react-notion-x/issues/135](https://github.com/NotionX/react-notion-x/issues/135). 
Found that in the class `notion-viewport` there's a CSS position `position: fixed` and that makes the overlay on the page that makes the user cannot interact with the page.
=> style: :art: change position in .notion-viewport to relative

packages/notion-types/src/block.ts, packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/styles.css
inspired by #166 
add block type and also add some simple stylesheet
***
also noticed default css variable is not variety enough just like `fg-color-1(~5)`
=> Add support for simple table

packages/notion-types/src/block.ts, packages/react-notion-x/src/block.tsx
Formatting can be null when there is no formatting. This caused an issue for some simple tables.
=> fixed simple tables having issues with no formatting

packages/react-notion-x/src/block.tsx
Simple Table is not working when there are empty cells in the table.
=> fix: notion simple table when there are empty cells

packages/notion-types/src/block.ts, packages/react-notion-x/src/block.tsx
PageId: 5995506f2c564d81956aa38711e12337
Header blocks now handle the toggle format.
=> added support for toggle header blocks

packages/react-notion-x/src/components/text.tsx, packages/react-notion-x/src/utils.ts
Changes to preserve the fragment identifiers in pageLinks. We use custom navigation links instead of notion's TOC in a lot of documents and this will help preserve that behaviour in notion-x.
The earlier PR (#150) looks abandoned. I've not attempted to add ids to all the blocks since the hash links that are automatically generated for headings are enough for our requirements.
---
Amazing work on the library btw. I'm frankly amazed this even exists. Thanks!
=> Preserve fragment identifiers in links

packages/notion-types/src/core.ts, packages/notion-utils/src/get-page-property.ts
support which marked with TODO 😁
Actually, the param `block` is not much useful (maybe `pageId`  which was `block.parent_id` would better), reserve it for non-breaking changes
***
also done an unit test later, but few of wrong type definitions which need be fix prevent me from using my test cases
=> add non-text support for getpageProperty 

packages/notion-client/src/notion-api.ts
```
Before all: Sorry I can't share the page as it's my working draft.
```
When grouping and sorting are both aplied on a table, seems that `getCollectionData` won't apply the filter.
I compared official website's API query:
```
{
"collection": {
"id": "70e01f9c-dbd3-46b6-8efc-df9ebb589b96",
"spaceId": "c8569e32-89f8-4ddf-ac21-adb5a19fdb24"
},
"collectionView": {
"id": "36a64343-6578-4e81-81a7-5e9355b769a9",
"spaceId": "c8569e32-89f8-4ddf-ac21-adb5a19fdb24"
},
"loader": {
"type": "reducer",
"reducers": {
"table_groups": {
"type": "groups",
"groupBy": {
"sort": {
"type": "manual"
},
"type": "multi_select",
"property": "_gbq",
"hideEmptyGroups": true
},
"filter": {
"filters": [
{
"filter": {
"value": {
"type": "exact",
"value": true
},
"operator": "checkbox_is"
},
"property": "fK<{"
}
], …
```
=> fix: notion table filters when grouping is also applied

packages/react-notion-x/src/eval-formula.ts, packages/react-notion-x/src/utils.ts
Notion's data is based off of UTC but before the Date would transform to the local time.
Made a change to make sure we are saving in UTC time.
Page to test: 43fb2254b7e3412ca461566f7a83918e
Before: was the 22nd even though it should be 23rd.
Now:
=> fixed date being one off for properties and formulas

packages/react-notion-x/src/components/property.tsx, packages/react-notion-x/src/styles.css
The library only shows a checkbox on a collection card without the checkbox's name. 
**This is what it looks like currently** 
**And this what it looks like on notion**
I've been able to implement this by adding the checkbox name [from the schema] to the collection cards.  Here is a link to the notion page  https://talented-work-a0b.notion.site/Checklist-128b92cbe975470c8a8594ad232cf3da
=> Show the checkbox text on collection card

packages/react-notion-x/src/styles.css
On a iPhone 12 Pro screen, horizontal padding is calculated as 7.8px which looks awful for such content-rich website:
On super.so the minimum padding is 24px. That's a lot so 16px would do it.
=> Widen horizontal padding on small screens

example/lib/preview-images.ts, example/next-env.d.ts, example/next.config.js, example/package.json, example/pages/[pageId].tsx, example/readme.md, example/yarn.lock, package-lock.json, package.json, packages/notion-types/src/maps.ts, packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/components/asset-wrapper.tsx, packages/react-notion-x/src/components/asset.tsx, packages/react-notion-x/src/components/lazy-image.tsx, packages/react-notion-x/src/context.tsx, packages/react-notion-x/src/renderer.tsx, packages/react-notion-x/src/styles.css, yarn.lock
- lots of misc bug fixes
- update some core deps (typescript, next.js, etc)
- fix custom image support focusing on `next/image` use case 🔥 
- normalize how preview images are loaded and supported for both custom and non-custom images
- re-enable and fix `medium-zoom`
- update the next.js example to use a custom image with preview images enabled via [lqip-modern](https://github.com/transitive-bullshit/lqip-modern)
@normdoow @pbteja1998 just a head's up that this is a larger update
=> General maintenance update

readme.md
- adds documentation on providing auth to the Notion Client for private pages
- Code Snippet provides implements node env
DEMO: You can preview the README.md at my branch here: https://github.com/ggiande/react-notion-x/tree/ggiande/doc-private-page-auth
This update does not reference any specific Notion page that is publicly available because it's about a private Notion page.
Fixes #267 
- README.md: added a guide on retrieving the necessary tokens from a cookie in the browser
=> ✍🏼README.md includes docs on using auth for private pages

packages/react-notion-x/src/styles.css
This style breaks dividers, and only applies when `hideBlockId` is enabled
This padding adds some weird borders around the sides of a divider
It also only applies when `hideBlockId` is enabled since it doesn't match `notion-block-{ID}`
`ID` 0be6efce9daf42688f65c76b89f8eb27
`URL` https://react-notion-x-demo.transitivebullsh.it/0be6efce9daf42688f65c76b89f8eb27
To reproduce, remove the ID from the divider's `notion-block` class name which is what `hideBlockId` would set it to
=> Remove styles inconsistency

packages/notion-compat/src/convert-block.ts
Add SimpleTable Block to notion-compat.
I found some unsupported items of API.
1. There is no API to get the column ID. Used the index instead.
1. The SimpleTable column has no width and color. API is not supported.
I have left a comment on these in the source code.
1. https://github.com/nakaiyusaku/react-notion-x/commit/1f0ab29f11ebd39f2dc5e35a369ba476d503d547#diff-e25fbbad19a8dad7ae798b5c4491230f038bc4a86b04862e7227bb01f95b116bR321
1. https://github.com/nakaiyusaku/react-notion-x/commit/1f0ab29f11ebd39f2dc5e35a369ba476d503d547#diff-e25fbbad19a8dad7ae798b5c4491230f038bc4a86b04862e7227bb01f95b116bR330
https://react-notion-x-official-api-demo.transitivebullsh.it/9d9814f3220a4b3bbc2481ad6fd7c913
=> Add SimpleTable Block to notion-compat

packages/notion-client/readme.md
I think the current documentation for `notion-client` doesn't do enough justice to how powerful it is.
I explain the shape of the response that `getPage` method is supposed to return and give example response.
cc368b47772a4a1aa36e1f52c507d20d
=> feat(docs): add explanation for notion-client

contributing.md
The name of the folder that contains examples for using React Notion X is `examples`, not `example`. I just fix this typo.
N/A
=> feat(doc): fix typo for examples folder

packages/notion-client/src/notion-api.ts
In some cases a content page id is not in the block object, this can cause a `TypeError: Cannot read property 'value' of undefined`
=> fix TypeError in addSignedUrls

packages/notion-client/src/notion-api.ts
Notion changes how their databases work a while back and updated how users can filter them. This update adds support for that newest update.
Now notion-react-x can show databases even if they have filters on them. This should work for all types of views.
multiple different text examples including older version of databases that still work.
84696b02b91d45a4a879ff572c23cc93
3271d83e87a14a42b5a53fd16c4339a7?v=ef3aeeb35e3045dc9b04abba22c10648
6f6138a8d9ab4e2b85a0f664d035b9a3?v=ca9b476a978d430a81ceac957b28dee7
a0cb6346eaba4a4f930a4c4206942b1e
=> FEAT: Added support for the newest version of database filters

packages/notion-client/src/notion-api.ts
Only add signed urls for `secure.notion-static.com` urls
Fix #331 
https://brave-iberis-6ea.notion.site/Videos-5af3d63c840e458e92c09c2ec6cd71b3
https://react-notion-x-demo.transitivebullsh.it/5af3d63c840e458e92c09c2ec6cd71b3
=> Only add signed urls for `secure.notion-static.com` urls

packages/react-notion-x/src/components/asset-wrapper.tsx, packages/react-notion-x/src/renderer.tsx
Added the ability for the react-notion-x user to set if they what image assets to be zoomable or not.
You can use the isImageZoomable on Renderer.
By default image assets are zoomable as before.
test page with images: 3492bd6dbaf44fe7a5cac62c5d402f06
=> added prop for isImageZoomable to renderer

packages/react-notion-x/src/block.tsx
Quote block can include several sub-blocks, but the render result only renders the first paragraph.
original:  
render result:  
d3e0c32cb40f4506a024a0672b40ae80
=> fix: missing sub-blocks in quote block

packages/react-notion-x/src/third-party/collection-view-board.tsx
Before boards only worked with grouped by "select" type. Notion changed it that you can group by about anything. So the fix is pulling the type that is used for  grouping. The change is backwards compatible as well.
There is currently an issue still where if multiple  views are added in Notion, the board may not appear because the data is with one of the other collectionview types.
Tested on this new  board: f4cd548ded6b42a7a2340d11111ef3be
Tested on this old board also: a899b98b7cdc424585e5ddebbdae60cc
=> fixed board views not working with new group by

packages/notion-client/src/notion-api.ts
Apparently  some collections can have some format data on board_columns_by even  when  they aren't board collelctions. This would mess up the payload for our collection query. and  end  up in retrieving no collection rows.
Found the issue on this page originally.  a0c071336c77426ea9925a5088d92ea0
Tested on 2fea615a97a7401c81be486e4eec2e94  and all the collections from the test workspace to makes sure everything works correctly.
=> Fixed groupBy board_coumns being added to non board collections query

packages/react-notion-x/src/components/page-icon.tsx
Added support for the new Notion built-in icons feature!
The icons are served from Notion at this endpoint: `https://www.notion.so/icons/<icon name>?mode=<dark or light>`
[Notion test page with an Icon](https://michaelcasadev.notion.site/Emojis-49f9e212d8cc443791b383f5c87e1d35)
=> Add support to new Notion built-in icons

packages/notion-client/src/notion-api.ts
Since `collectionView` is an optional arg in `getCollectionData()`, calling it without would throw an error because of a missing nullish check.
86b15a89dd4846699383be4476beafa9
=> Add missing optional chaining in getCollectionData function

packages/react-notion-x/src/third-party/collection-card.tsx
this adds url  links back into board and gallery collections.  Before the a tags where removed. I believe this was for the concern of a tags being nested. But Notion implements it this way and there doesn't seem to be an issue with the a tags nested.
d2692a6a4a1b420395e4979a2c05c7b4?v=6f12dc69ae7549f985bdbaa5ca81623f
=> allow a links to be used in board and galleries

packages/react-notion-x/src/context.tsx, packages/react-notion-x/src/styles.css, packages/react-notion-x/src/third-party/collection-card.tsx
This is a cool one. added a feature where url properties can become the card link for gallery views and board views. By  default it is not enabled. Have to set `isLinkCollectionToUrlProperty` to true in NotionRenderer to turn it on.
Also made a url property  that is visible be a form  subbmision so it can be nested.
d2692a6a4a1b420395e4979a2c05c7b4?v=6f12dc69ae7549f985bdbaa5ca81623f
=> added feature where collection cards can link out to the url property

packages/react-notion-x/src/third-party/collection-card.tsx
Issue where url properties are empty and we were accessing a null value.
2ba1d59cc64a4f539a100922a8d312e9
=> fixed url properties that may be empty

packages/notion-utils/src/get-page-image-urls.ts, packages/react-notion-x/src/components/asset.tsx
Notion made a change where some pages use file.notion.so as their signed urls.
These srcs aren't working currently.
This is a hot fix to at least get it working.
Using the block image src instead just in this case.
d9cc0ffee90e41c4b3ab1f450c346ba7
Don't have a ton of examples to play around with because my Notion workspace isn't producing the file.notion.so srcs. 😅
=> Hot fix -  new image src with file.notion.so not working

packages/react-notion-x/src/block.tsx
You can set table row background color in Notion, but it's not reflected in React Notion X
https://egoist.notion.site/react-notion-x-patch-1-2843d872184a419a9dde2ba1ad1a64db
=> fix: set table row background color

packages/notion-utils/src/normalize-title.ts
I love using react-notion-x on my blog. Thanks again. 
I would like to add Japanese hiragana and katakana to solve the problem similar to #176.
Japanese is written in a mixture of kanji, hiragana and katakana. 
Example: https://jsfiddle.net/uw5m9kts/6/
In [RFC-1738](https://www.ietf.org/rfc/rfc1738.txt), It basically supports us-ascii sets, browsers will encode japanese charaters automatically too.
=> feat: support for normalize japanese hiragana and katakana title

packages/react-notion-x/src/styles.css
Hi, I found an issue in Notion Toggle that the child element goes over toggle width when using the nootion link embed. I simply applied the width 100% through the override, and the child element did not overflow, so I'm PRing if it's applicable.
=> Fix: notion toggle's child Element overflow issue

packages/react-notion-x/src/components/asset.tsx
The PDF content doesn't display from the first page.Official react-notion demo with pdf doesn't display from the frist page and I can't scroll it to the first page.
It caused by the _display: flex_ at pdf asset, so I change this to _block_.
Solve the issue #411
=> fix pdf styling

package.json, packages/notion-types/src/collection.ts, packages/react-notion-x/src/third-party/collection.tsx
In the settings for Collection Views, there's an option to hide the title of the collection.
This PR makes it so that the setting is respected, by looking at the correct field off of `format`.
(PS: Thank you for building this ❤️)
Collection-View-Title-test-7700cfb836854d229285d85ffd9e913a
Hidden titles:
Shown titles:
(The other headings are just `<h2>`s :)
=> Respect hiding collection view titles if setting is set

packages/react-notion-x/src/styles.css
Fix the problem that the notion-external-mention svg icon is displayed abnormally on Safari
current:
after fixed:
https://react-notion-x-demo.transitivebullsh.it
=> fix: the notion-external-mention svg icon is displayed abnormally on Safari

packages/notion-compat/src/notion-compat-api.ts
@transitive-bullshit Can we get rid of this console.log() please, it clutters the logs.
Also, no TS types are available for `"notion-compat": "^6.16.0",` version.
There is also no `@types/notion-compat`, so TS complains when importing it, and I have to ts-expect-error.
=> hotfix / remove log

packages/react-notion-x/src/components/text.tsx
Show date and time for reminders.
Before
After
5a441e784a104ed685dcad91cb975c16
=> fix: show reminder date and time

packages/notion-client/src/notion-api.ts
**Problem:** The search function is currently broken: we get a mysterious 405 error when we prop open the dev console and inspect the search request:
It turns out that Notion slightly changed the API for search, resulting in the way the library `notion-client` sends the API request to Notion for searching to be broken and throw an error:
*The request body in the above screenshot was generated by `notion-client` and I just put it in Postman to show the error that is thrown by the Notion API.*
Luckily this was a quick fix! I went to Notion and performed a search and inspected how they sent the API request, and noticed a slight difference:
For the `sort` key, `notion-client` currently sends the following:
```json
"sort": "Relevance"
```
While the Notion web app sends:
```json
"sort": { …
```
=> Fix broken search function

packages/react-notion-x/src/components/eoi.tsx, packages/react-notion-x/src/styles.css
(cherry picked from commit 6c990033c7a8d82a816121b7d8fc82dcd076cfa5)
fix  the eoi component displays an exception under the block type
error ui:
correct ui
=> fix: the eoi component displays an exception under the block type

packages/notion-types/src/block.ts
When the PR #563 was merged the types were not updated and this broke the builds and typing.
After this is added the builds should work again.
=> Add missing new attribute 'card_cover_position' to BasePageBlock type

packages/react-notion-x/src/third-party/collection-card.tsx
This is continuation for #567 where I fixed the changed types so that the builds work again after they broke from merging #563.
Before these changes:
```
$ yarn test:prettier
yarn run v1.22.22
$ prettier '**/*.{js,jsx,ts,tsx}' --check
Checking formatting...
[warn] packages/react-notion-x/src/third-party/collection-card.tsx
[warn] Code style issues found in the above file. Forgot to run Prettier?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
So I then ran: `yarn test:prettier --write`
And the result after these changes:
```
$ yarn test:prettier
yarn run v1.22.22
$ prettier '**/*.{js,jsx,ts,tsx}' --check
Checking formatting...
All matched files use Prettier code style!
✨  Done in 2.72s.
```
This should [fix …
=> Fix prettier linting issues from #563

packages/notion-types/src/block.ts
Add missing table_block_row_header to TableBlock type.
When setting the first row of the table as the header, the table block has this field.
=> fix: add missing table_block_row_header to TableBlock type

packages/react-notion-x/src/styles.css
@transitive-bullshit @normdoow  This is pr for issue #513.
/react-notion-x/packages/react-notion-x/src/styles.css
`.notion-h {
display: inline-block;
}`
Changed the code above as below:
`.notion-h {
display: inline;
}`
=> Fix: fixed toggle issue

packages/react-notion-x/src/styles.css, packages/react-notion-x/src/third-party/collection-view-board.tsx
Fix title for empty group on board view, using the property name instead of a static title.
Board view grouped by **Priority** property:
Before
After
`16f256fbf9b54bc6b4befe13ba74faeb`
=> fix: empty group title for board view

packages/notion-utils/src/normalize-title.ts
Just like adding Chinese (https://github.com/NotionX/react-notion-x/pull/177) and Japanse (https://github.com/NotionX/react-notion-x/pull/433), fix for Korean titles.
For those who are facing error for their own languages, use `includeNotionIdInUrls: true` in the `site.config.ts` to bypass the issue.
=> feat:support for normalize korean title

packages/react-notion-x/src/styles.css
There is an additional padding of 3px at the top & bottom of the page which is not needed. It's highlighted in green in the picture below
The problem is also visible here: https://react-notion-x-demo.transitivebullsh.it/
=> Remove additional padding in notion-frame

packages/react-notion-x/src/context.tsx, packages/react-notion-x/src/next.tsx, packages/react-notion-x/src/types.ts, readme.md
This PR updates next.js component wrapper to support new Image component from Next.js 13.
The legacy Image component(`next/legacy/image`) will be also supported by changing `nextImage` prop to `nextLegacyImage` prop.
=> Add Next.js 13 new Image component support

examples/full/components/NotionPage.tsx, examples/minimal/components/NotionPage.tsx, packages/notion-client/package.json, packages/notion-compat/package.json, packages/notion-types/package.json, packages/notion-utils/package.json, packages/react-notion-x/package.json
This PR allows 'hot-reload' on pnpm dev to also watch the packages for changes
=> fixed pnpm dev

packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/styles.css
See issue https://github.com/NotionX/react-notion-x/issues/565
Notion recently introduced two changes to callouts:
- There is no longer a forced text title and instead we just have block contents, allowing blocks like `<h1>` at the top of a callout.
- You can remove the icon from the callout entirely (this was me 😉).
This led to some minor visual issues with react-notion-x.
In this PR, we: 
- Remove the icon entirely when it is missing 
- Removes the top padding/margins on the callout text's first child.
1425cb08cf2c80efb771e6010d8dac21
**Notion**
**Main [before change]**
https://react-notion-x-demo.transitivebullsh.it/1425cb08cf2c80efb771e6010d8dac21
**After change**
Old callouts are fine too
(Note: there seems to be a funny bug with adjacent headings being rendered on the same line 😛. …
=> Fix callout spacing for new callouts (sans icons)

packages/react-notion-x/src/components/lite-youtube-embed.tsx
I asked feedback about my website and my friend shared great point that the default Youtube preview images are quite blurry.
I learned how img srcsets work and added support for high quality alternative `webp` photos.
I tested this on locally with chrome and it skips completely the default jpg and preloads only the highest available image on desktop.
0f7d9b7aec8b4d16a064886b245badef
=> Add support for high quality and responsive Youtube preview images

packages/notion-client/src/notion-api.ts, packages/react-notion-x/src/third-party/pdf.tsx
When trying to display a PDF file, I've figured out that notion is using a new bucket url to serve their files and it impacts how this library handles url signing. 
- Old files start with: `https://s3-us-west-2.amazonaws.com/secure.notion-static.com/...`
- New files start with: `https://prod-files-secure.s3.us-west-2.amazonaws.com/...`
Including `prod-files-secure` prefix when identifying a private url, fixed the issue.
Other than that, the PDF component is using an outdated `pdfjs-dist` cdn url, so i've updated it.
- PDFs not being displayed: `34d650c65da34f888335dbd3ddd141dc`
=> Fix private file signed url generation

packages/notion-client/src/notion-api.ts
Notion file uploads now append `attachment:` to the file identifier instead of the s3 url.
Therefore the source is also a valid source if it includes `attachment:` in the source text.
Here's an example of a Notion page
1b2d3f870f0080caae0bc0b2766cf31f
=> fix: look for `attachment:` in file upload source

packages/react-notion-x/src/third-party/code.tsx
- `prismjs` is under the hood, it addes `language` and `tabIndex` attributes to `pre` tag but the ssr results doesn't have these, so **hydration error** occures.
=> fix(code): code hydration error

packages/notion-types/src/core.ts, packages/react-notion-x/src/components/link-mention.tsx, packages/react-notion-x/src/components/text.tsx, packages/react-notion-x/src/styles.css
- Fixed an issue where the newly introduced "Link Mention" feature in Notion was unsupported, causing an "unsupported text format" error.
- Now, it's correctly rendered in a way similar to Notion's functionality.
=> feat(text): support Link Mention format

packages/react-notion-x/src/components/text.tsx
* #609
@transitive-bullshit Thanks for merging my PR!
but It seems I missed running the eslint check for sorting import order. This PR is to fix that so it can pass the merge process.
Also, I'm gonna update the contribution guide and add a lint check to the GitHub Actions for PRs and pushes, and submit a new PR for that as well. 
* #615
=> fix(eslint): imports sort lint

packages/react-notion-x/src/components/link-mention.tsx
This PR adds `referrerPolicy="same-origin"` to `<img>` elements inside the `LinkMentionPreview` component.
Some external preview thumbnails (such as images hosted on Naver Blog) were not being displayed due to cross-origin Referrer-based access restrictions. These servers often block image requests with foreign Referer headers to prevent hotlinking.
By explicitly setting `referrerPolicy="same-origin"`, we suppress the `Referer` header on cross-origin image requests, improving compatibility with such services and preventing image preview failures.
This fix should help resolve thumbnail breakage for many Notion links that point to external content providers with strict CORS or Referer policies.
`aa408b24c0e74b61b0165cf937975663`
<table>
<tr>
<td align="center"><strong>before</strong></td> …
=> fix(link-mention): add `referrerPolicy="same-origin"` to image tags to prevent preview issues

packages/react-notion-x/src/styles.css, packages/react-notion-x/src/third-party/collection-view-list.tsx
In Notion, when using a collection_view of type list, the list items only display the page title without showing the corresponding page icon.
1. Import the PageIcon component in the `collection-view-list.tsx` file
2. Add the PageIcon component to the title rendering section of list items
3. Modify the CSS styles to ensure the icon and title are displayed horizontally in the same line
Before
After
1ec1578febe580ad8dc5fca79f736e30
=> fix: display page icons in collection list view

packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/styles.css
Fixes #628 
Simple tables always show the first row with header styling (background color), regardless of whether header settings are enabled. This is inconsistent with Notion's native behavior.
This PR fixes table header rendering to only apply styling when explicitly enabled:
- Row headers (first row): Only styled when `table_block_column_header` is true
- Column headers (first column): Only styled when `table_block_row_header` is true
Note: There's an interesting naming confusion in Notion's API - table_block_column_header actually controls row headers, while table_block_row_header controls column headers. This PR maintains the original field names for API compatibility but implements the correct behavior.
**After**
1eb1578febe58070a07edf70bd34025d
=> feat: table header rendering optimization

packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/styles.css, packages/react-notion-x/src/utils.ts
Fixes #548 
In the current implementation, all levels of nested numbered lists use the same decimal numbering style (1, 2, 3...), regardless of nesting depth. This makes it difficult to distinguish between different levels of nested lists and doesn't follow standard document formatting conventions.
This PR introduces proper styling for nested numbered lists by:
1. Adding a new getListNestingLevel function to determine the nesting level of a list item
2. Adding a new getListStyle function to cycle through appropriate list styles based on nesting level
3. Modifying the list rendering logic to apply the correct style to each level of nested lists
**Before**
**After**
1e31578febe580e5847ac4314e304b02
=> Add multi-level numbered list styles with proper nesting

packages/notion-client/src/notion-api.ts
Fixes #650, #649, #648.
"Unofficial" Notion API changed its request shape! Particularly, it now requires `version = "v2"` and `groupSortPreference` slightly changed.
91c2be1a6018421ab9062e3f045eaa59
Before
After
=> Fix for groups v2 api request issues

packages/notion-client/src/notion-api.ts
`getBlocks` uses `syncRecordValues` endpoint which is now deperecated and no longer works unfortunatly. This PR update that to the working endpoint `syncRecordValuesMain` 
Related to #659 (suggest `beforeRequest` hook) and #661 (suggest package patching)
0fa06897b70f4e78876324cd9df76356
=> fix: update endpoint in getBlocks method to syncRecordValuesMain

packages/notion-utils/src/get-all-pages-in-space.ts, packages/react-notion-x/src/third-party/collection-utils.ts, packages/react-notion-x/src/third-party/eval-formula.ts, packages/react-notion-x/src/third-party/property.tsx
The `getAllPagesInSpace()` function in `notion-utils` is valuable for sitemap generation and SSG. However, the current implementation fails to retrieve subpages within collections. This is because it searches for `blockIds` inside `CollectionQueryResult`, where the results are typically not present.
Upon investigation, I found that the relevant subpage data primarily resides in `CollectionQueryResult.collection_group_results`, not in the main `CollectionQueryResult` itself.
BTW, I fixed #616 to remove annoying warnings during building.
You can verify this behavior by logging the results during the build process.
=> Fix collection traverse

packages/react-notion-x/src/styles.css
Background color not filling full width in notion header
added width 100% in notion-h style
Notion Page Id : 148e895fae8680ed8002c5966af7771b
=> fix: header background color set completely
