packages/react-notion-x/src/styles.css
```
.notion-page-link:hover {
```
exists on 480 line.
=> Remove same css

packages/react-notion-x/src/components/asset.tsx
Issue here: https://github.com/NotionX/react-notion-x/issues/34#issuecomment-785559577
Other Images still look good
=> Fixed image height when the image is in a column

packages/react-notion-x/src/components/asset.tsx
Id of page to test: cfdc513910024e91b872648eda848986
Pretty straight forward change!
=> Added support for Wistia embed videos

packages/react-notion-x/src/components/asset.tsx
Page with loom embeds: ede33e3f0199472bbbb9d08e03a2b328
=> added support for loom embeds

example/package.json
https://github.com/NotionX/react-notion-x/issues/85#issuecomment-860096671
=> fixed multiple react apps

packages/notion-types/src/block.ts, packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/components/asset.tsx
Notion page Id for excalidraw: 9a1e657d80ab443480d694e9e4af4e09
Notion page Id for cloudapp video: 8b582c3ea03748d8bc35ca6748820531
=> Added support for excalidraw blocks and cloudapp videos

packages/notion-utils/src/get-page-table-of-contents.ts, packages/react-notion-x/src/block.tsx
pageBlock.value.content  does not contain nested blocks
https://github.com/craigary/nobelium/issues/138#issue-907925850
=> fixed TOC display in columns

packages/notion-types/src/block.ts, packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/components/asset.tsx
Test page with codepen: 0c88d1b28ee64941b8b97ba7b8c59bc9
=> added support for codepen blocks

packages/notion-utils/src/get-page-table-of-contents.ts
Use a conditional on top of the nullish coalescing operator
=> Check for undefined in block property

packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/styles.css
Test Page: https://michaeldevc.notion.site/Testing-new-callout-blocks-3229861ab6254424bf0c8fd4c1fc9dc8
=> Support for new Notion callout blocks

packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/context.tsx, packages/react-notion-x/src/types.ts
=> feat: added custom checkboxes

packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/components/checkbox.tsx, packages/react-notion-x/src/components/property.tsx
fix a couple of issues with the custom checkbox changes from: https://github.com/NotionX/react-notion-x/pull/119
=> fixed checkboxes.

example/pages/[pageId].tsx, packages/notion-client/src/notion-api.ts
Fixes all tables except for board tables. They have some extra parameters that need sent. Will have to fix that later as a followup.
=> fixed notion api query collection hitting 400 error

packages/notion-client/src/notion-api.ts
@normdoow Looks like there is some other change to the queryCollection API too.
=> fix: query collection API

packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/types.ts
Hey, this is a small PR to add support for custom `callout` blocks. IMO this should be an option for all types of blocks, so that it can allow the user to customize the block however they want.
=> feat: Add support for custom callout blocks

packages/react-notion-x/src/block.tsx
the old PR is here: #169 
the issue is here: #168
=> fix: code block content lost

packages/react-notion-x/src/block.tsx
Testing on 9d9814f3220a4b3bbc2481ad6fd7c913
=> fixed simple table not supporting text with attributes

packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/context.tsx, packages/react-notion-x/src/types.ts
Implementation about issue https://github.com/NotionX/react-notion-x/issues/240.
=> feat: support optional custom embed component

lerna.json, packages/react-notion-x/package.json, packages/react-notion-x/tsup.config.ts, tsconfig.base.json
- also adds `exports` and `typesVersions` to package.json
=> Add dev and prod outputs to make react-notion-x easier to debug during development

packages/react-notion-x/src/styles.css
=> fix(css): improve search pane color in dark mode.

packages/notion-types/src/block.ts
types missing "breadcrumb".
https://nabettu.notion.site/react-notion-x-PR-db831bbe0176439f80c487efdc1161e6
=> add type breadcrumb

packages/notion-types/src/block.ts
Pleaze merge after this PR  https://github.com/NotionX/react-notion-x/pull/275
add type miro
https://nabettu.notion.site/react-notion-x-PR-db831bbe0176439f80c487efdc1161e6
=> add type miro

packages/notion-types/src/block.ts, packages/react-notion-x/src/components/asset-wrapper.tsx, packages/react-notion-x/src/components/asset.tsx
I added support to the new Notion ~~image~~ assets alignment system.
[Notion page with some images alignment combinations](https://michaelcasadev.notion.site/Image-alignment-de3e8caf76aa49b18f1a6aea61de3c70)
=> Support for new assets alignment

packages/notion-client/src/notion-api.ts
Commit mainly to make  a change  so we can redeploy the latest version to npm.
=> removed unneeded comment

packages/notion-client/src/notion-api.ts
One last time to make  the deploy go through on npm.
=> one more time

packages/react-notion-x/src/map-image-url.ts
fix issue where cover image does not show
Example: 3ff88ffb9f2745ab8090c497f4ecdcae
=> fix issue where cover image does not show

packages/react-notion-x/src/components/header.tsx, packages/react-notion-x/src/context.tsx, packages/react-notion-x/src/renderer.tsx
added onHideSearch event
0be6efce9daf42688f65c76b89f8eb27
=> added onHideSearch event

packages/react-notion-x/package.json, packages/react-notion-x/src/styles.css, packages/react-notion-x/src/third-party/collection.tsx, yarn.lock
Notion updated how their databases look  like with multiple views. More info here: https://github.com/NotionX/react-notion-x/issues/383
Updated the dropdown to look more like Notion does currently. As of now,  when there are too many tabs it breaks and goes to the next line.  Not exactly like Notion  but I  think looks fairly good.
2fea615a97a7401c81be486e4eec2e94
=> added new tabs for multiple views

packages/react-notion-x/src/renderer.tsx
=> forgot to add isLinkCollectionToUrlProperty to the renderer props

packages/react-notion-x/src/third-party/collection-card.tsx
=> fixed bug where linproperties could be null

packages/react-notion-x/src/third-party/property.tsx
let keyword redefined the variable, which set the return value of the entire function to undefined, discarding the calculated value
067dd719a912471ea9a3ac10710e7fdf
=> fix redeclaration of variable in formula calculation

packages/react-notion-x/src/components/asset.tsx
This PR resolves the issue #55 
`130868ef58d949f4add8cf1da983fc16` (as mentioned in the issue).
=> Fix: fixed typeform auto focus issue

packages/react-notion-x/src/components/search-dialog.tsx, packages/react-notion-x/src/third-party/modal.tsx
Added app-element to the react-modal, earlier it was giving warning, which is now fixed in this PR.
=> Fix: setting app-element in react-modal Modal component

packages/notion-utils/src/format-notion-date-time.ts
This PR fixes the issue: #489 and also for the safari browser. 
067dd719a912471ea9a3ac10710e7fdf (Default Demo Test Page)
=> Fix: time on EOI component for firefox and safari browser

packages/notion-types/src/block.ts, packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/components/asset.tsx
This PR resolves issue: #197 
`3ebfc89c91c74ca8a17ef320fd740eea`
=> feature: added replit support as embed

packages/react-notion-x/src/components/eoi.tsx, packages/react-notion-x/src/components/mention-preview-card.tsx, packages/react-notion-x/src/styles.css
fix: mention-preview-card ui
https://www.notion.so/Notion-Test-Suite-067dd719a912471ea9a3ac10710e7fdf
=> fix: mention-preview-card

packages/notion-utils/src/get-all-pages-in-space.ts
when looping get all pages, it's possible that encountered alive===false block/page, it should be skipped.
=> skip pages which is not alive.

packages/react-notion-x/src/components/asset.tsx
Tella embeds don't work right now and this should help!
Coming soon!
=> add tella video source support

packages/notion-types/src/collection-view.ts, packages/notion-types/src/maps.ts
There is a `reducer` type of collection view, which is `table` type when created on Notion Website.
d297b76916ff4749b49648ac9984c358
=> feat: support reducer result

packages/notion-utils/src/get-page-table-of-contents.ts
Headings in synced blocks are not shown in the TOC block with the current version of notion-utils (v6.16.0). This PR fixes the issue.
| Notion | react-notion-x |
|---|---|
| ![PixelSnap 2023-03-31 at 22 37 13](https://user-images.githubusercontent.com/7194254/229152066-3d69754b-20a0-40b5-9da6-46906dd2b351.png) | ![PixelSnap 2023-03-31 at 22 35 55](https://user-images.githubusercontent.com/7194254/229152083-3a387e3c-357a-4e6f-976b-9580fec3312b.png) |
`f1d446655c364e86985faa7dc9181243`
=> fix: headings in synced blocks not shown in toc

packages/react-notion-x/src/block.tsx, packages/react-notion-x/src/components/asset.tsx, packages/react-notion-x/src/components/audio.tsx, packages/react-notion-x/src/components/file.tsx
#441 Add spaceId to src for files(audio, file, video...)
=> Fix #441- Fix files are not working

packages/notion-client/src/notion-api.ts
Link issue: https://github.com/NotionX/react-notion-x/issues/583
The search functionality is currently broken due to missing field in search filter. This MR is to add that field into search filter.
=> fix: broken search
